### ISSUE TITLE
Need enhancement on translating technique

### ISSUE THREAD

**Issue by nitinkumar30** [nitinkumar30/language-translator#1]
I want this to translate on every SPACE pressed. Like after writing `Mera`, it should translate to `My` when translating from Hindi to English. A demo website is [this](https://hindityping.info/). 

Need the following logic to be implemented:
- On every space pressed, the function of the button should run the trigger

The algorithm should be like below:

```
Step 1:write text

Step 2:if (space pressed):
    		translate previous word/replace the word with translated text
```

Working on this currently, but if you feel, you can also take this up.

**Comment by LostAnurag** [comment]
I'll try!

**Comment by nitinkumar30** [comment]
Completed the enhancement as in [branch 3.0](https://github.com/nitinkumar30/language-translator/tree/3.0).
